logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.50.103.62:3306/db_InternA?characterEncoding=UTF-8&serverTimezone=UTC
    username: interna
    password: test1234$
   
  security:
    jwt:
      secret: asdf123asdf
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 29010893dc4173be214f7ca77ce327d1
            client-secret: lBCmxqDN1wITFdZB9m7WlSHuZ93w2dsV
            scope: profile-nickname, account-email, brithday
            client-authentication-method: POST
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  
    